
general.import = [
  # "~/.config/alacritty/themes/tokyo_night.toml",
] # same format as this file


[window]
opacity = 1

[window.padding]
x = 10
y = 10

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 50000
multiplier = 3

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"


[terminal]

[terminal.shell]
program = "/usr/bin/zsh"
