format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$fill\
$package\
$c\
$golang\
$lua\
$python\
$aws\
$nodejs\
$rust\
$cmd_duration $jobs $time\
$line_break\
$character"""

[git_commit]
commit_hash_length = 4

[nodejs]
format = "[$symbol($version )]($style)"

[rust]
format = "[$symbol ($version )]($style)"

[fill]
symbol = " "

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vicmd_symbol = "[â®](green)"

[git_branch]
symbol = "ï˜"

[git_state]

[git_metrics]
disabled = false

[directory]
style = "blue"
read_only = " ï ½"
truncation_length = 0
truncate_to_repo = false

[git_status]
conflicted = '= â†’ ${count}  ' # This branch has merge conflicts.
ahead = 'îª  â†’ ${count}  '
behind = 'îª â†’ ${count}  '
diverged = 'ó±¡· â†’ ${count}  '
up_to_date = ' '
untracked = '? â†’ ${count}  '
stashed = 'ï…• â†’ ${count}  '
modified = 'ï‘„ â†’ ${count}  '
staged = 'î«´ â†’ ${count}  '
renamed = 'Â» â†’ ${count}  '
deleted = 'âœ˜ â†’ ${count}  '
format = '([$all_status$ahead_behind]($style))'

[jobs]
symbol = "ï€“"
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[package]
format = '[$symbol$version]($style) '
symbol = 'ğŸ“¦ '
version_format = 'v${raw}'
style = 'bold 208'
display_private = false
disabled = false

[aws]
symbol = "îŒ½"
format = "[$symbol ($version )]($style)"

[c]
symbol = "î˜"
format = "[$symbol ($version )]($style)"

[golang]
symbol = "î˜§"
format = "[$symbol ($version )]($style)"

[lua]
symbol = "î˜ "
format = "[$symbol  ($version )]($style)"

[python]
symbol = "îˆµ"
format = "[$symbol ($version )]($style)"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"
